version: '3'
services:
  web:
    container_name: docker-agri-nginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled:/etc/nginx/conf.d/sites-enabled
      - ./nginx/logs:/var/log/nginx
      - ../../Projects/agri_map:/var/www/agri_map
    env_file: './.env'

  #Agri map
  couchbase:
    container_name: docker-couchbase-agri
    # image: couchbase:latest
    build:
      context: ./couchbase
    restart: always
    deploy:
      replicas: 1
    volumes:
      - ./couchbase:/opt/couchbase/var 
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
    env_file: './.env'
    tty: true

  agri:
    container_name: docker-agri-server
    # platform: linux/amd64
    build:
      context: ./server
    restart: always
    volumes:
      - ../../Projects/agri_map:/var/www/agri_map
    ports:
      # - 8888:80
      - 6042:6042
      - 5023:5023
      - 5013:5013
    env_file: './.env'
    tty: true
    links:
      - couchbase
    depends_on:
      - couchbase